[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['corepack enable', 'pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm build', 'pnpm postbuild']

[start]
cmd = 'pnpm start'
