[build]
builder = "dockerfile"

[deploy]
numReplicas = 1
startCommand = "serve -s .out -l ${PORT:-3000}"
healthcheckPath = "/"
healthcheckTimeout = 30

[variables]
NODE_ENV = "production"
PORT = "3000"
